name: Linux Client (dotnet build and test)

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  os-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version:  |
            6.0.x
            7.0.x
            8.0.x
        env:
          DOTNET_INSTALL_DIR: /usr/share/dotnet
      - name: Clone and run Authentication
        run:  |
          git clone https://github.com/EasyMicroservices/Authentications-Microservice.git
          cd Authentications-Microservice
          dotnet run --project src/CSharp/EasyMicroservices.AuthenticationsMicroservice.WebApi/EasyMicroservices.AuthenticationsMicroservice.WebApi.csproj &
          AUTH_PID=$!
          echo "Started Authentication Service with PID $AUTH_PID"
          cd ..
        shell: bash
      - name: Clone and run WhiteLabel
        run: |
          git clone https://github.com/EasyMicroservices/WhiteLabels-Microservice.git
          cd WhiteLabels-Microservice
          dotnet run --project src/CSharp/EasyMicroservices.WhiteLabelsMicroservice.WebApi/EasyMicroservices.WhiteLabelsMicroservice.WebApi.csproj &
          WHITELABEL_PID=$!
          echo "Started WhiteLabel Service with PID $WHITELABEL_PID"
          cd ..
      - name: Restore dependencies
        run: dotnet restore ./src/CSharp/EasyMicroservices.IdentityMicroservice.Client.sln
      - name: Build
        run: dotnet build ./src/CSharp/EasyMicroservices.IdentityMicroservice.Client.sln --no-restore
      - name: Test
        run:  |
          dotnet test ./src/CSharp/EasyMicroservices.IdentityMicroservice.Client.sln --no-build --verbosity normal -f net7.0
