name: NuGet Push Public

on: [workflow_dispatch]

jobs:
  build-test-prep-push:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            8.0.x
      - name: Clone and run Authentication
        run:  |
          git clone https://github.com/EasyMicroservices/Authentications-Microservice.git
          cd Authentications-Microservice
          dotnet run --project src/CSharp/EasyMicroservices.AuthenticationsMicroservice.WebApi/EasyMicroservices.AuthenticationsMicroservice.WebApi.csproj &
          AUTH_PID=$!
          echo "Started Authentication Service with PID $AUTH_PID"
          cd ..
        shell: bash
      - name: Clone and run WhiteLabel
        run: |
          git clone https://github.com/EasyMicroservices/WhiteLabels-Microservice.git
          cd WhiteLabels-Microservice
          dotnet run --project src/CSharp/EasyMicroservices.WhiteLabelsMicroservice.WebApi/EasyMicroservices.WhiteLabelsMicroservice.WebApi.csproj &
          WHITELABEL_PID=$!
          echo "Started WhiteLabel Service with PID $WHITELABEL_PID"
          cd ..
      - name: Restore dependencies
        run: dotnet restore ./src/CSharp/EasyMicroservices.IdentityMicroservice.sln
      - name: Build
        run: dotnet build ./src/CSharp/EasyMicroservices.IdentityMicroservice.sln --no-restore
      - name: Test
        run: dotnet test ./src/CSharp/EasyMicroservices.IdentityMicroservice.sln --no-build --verbosity normal
      - name: Create the package
        run: dotnet pack ./src/CSharp/EasyMicroservices.IdentityMicroservice.sln --output nupkgs
      - name: Publish the package to NuGet.org
        run: dotnet nuget push nupkgs\*.nupkg -k ${{secrets.NUGET_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate